#!/bin/sh
BIN=$1
OUT=$2
NAME=$3

SECTION_NAME=".user_programs"

cat > "$OUT" << EOF
# autogenerated assembler file for user program ${NAME}

# start symbol
    .p2align 12 # 2^12 = 4096
    .section $SECTION_NAME, "a"
    .global __USER_${NAME}_START
__USER_${NAME}_START:

# binary included here
    .incbin "$BIN"

# end symbol
    .p2align 12 # 2^12 = 4096
    .section $SECTION_NAME, "a"
    .global __USER_${NAME}_END
__USER_${NAME}_END:

EOF

