#!/bin/sh
BIN=$1
OUT=$2
NAME=$3

cat > "$OUT" << EOF
# autogenerated assembler file for user program ${NAME}
.global __USER_${NAME}_START
.global __USER_${NAME}_END
.p2align 12 # 2^12 = 4096
__USER_${NAME}_START:
.incbin "$BIN"
__USER_${NAME}_END:
EOF

