#!/bin/sh
OUT=$1; shift

USER_PROGS="$*"
NUM_PROGS=$#

# shellcheck disable=SC2086
STRIPPED_USER_PROGS=$(basename -as .c $USER_PROGS)

{
cat <<EOF
// autogenerated file

#include "sections.h"
#include <stddef.h>
#include <stdint.h>

const size_t num_user_programs = $NUM_PROGS;

EOF

for program in $STRIPPED_USER_PROGS; do
    echo "SECTION_DECLARE(USER_$program);"
    echo "SECTION_IMPL(USER_$program, SECTION_TYPE_USER_PROGRAM);"
done
echo

echo "const Section user_programs_data[$NUM_PROGS] = {"
for program in $STRIPPED_USER_PROGS; do
    echo "    SECTION_USER_$program,"
done
echo "};"

echo "const Section* user_programs = (const Section*) &user_programs_data;"
} > "$OUT"
