#!/bin/sh
INPUT_EXEC=$1
NAME=$2
OUTPUT=$3

OBJCOPY=${OBJCOPY:-llvm-objcopy}

BIN_NAME="$NAME.bin"

# user BIN (fully-expanded memory image)
${OBJCOPY} --set-section-flags \*=alloc,contents --output-target=binary "$INPUT_EXEC" "$BIN_NAME"

cat > "$OUTPUT" << EOF
# autogenerated assembler file for user program ${NAME}
.global __USER_${NAME}_START
.global __USER_${NAME}_END
.p2align 12 # 2^12 = 4096
__USER_${NAME}_START:
.incbin "$BIN"
__USER_${NAME}_END:
EOF

