#pragma once

#ifdef DEBUG
#define DEBUG_EXAMPLE_PROCESSES 1
#define DEBUG_MAP_ADDRESS 1
#define DEBUG_PAGE_ALLOC 1
#define DEBUG_PRINTF 1
#define DEBUG_ACTIVATE_TABLE 1
#define DEBUG_ATOI 1
#define DEBUG_SOFTWARE_INTERRUPTS 1
#define DEBUG_SWITCH 1
#define DEBUG_SYSCALL 1
#define DEBUG_USER_TRAPS 1
#define DEBUG_CLEAN_PROCESS 1
#define DEBUG_SECTIONS 1
#define DEBUG_ALIGN 1
#define DEBUG_EXIT 1
#define DEBUG_DEVICE_TREE 1
#define DEBUG_DEVICE_TREE_SEARCH 1
#define DEBUG_LIST 1
#define DEBUG_TESTS 1
#define DEBUG_TIMER_INTERRUPTS 1
#define DEBUG_ALLOCATE_PROCESS 1
#endif

#ifndef DEBUG_EXAMPLE_PROCESSES
#define DEBUG_EXAMPLE_PROCESSES 0
#endif

#ifndef DEBUG_MAP_ADDRESS
#define DEBUG_MAP_ADDRESS 0
#endif

#ifndef DEBUG_PAGE_ALLOC
#define DEBUG_PAGE_ALLOC 0
#endif

#ifndef DEBUG_PRINTF
#define DEBUG_PRINTF 0
#endif

#ifndef DEBUG_ACTIVATE_TABLE
#define DEBUG_ACTIVATE_TABLE 0
#endif

#ifndef DEBUG_ATOI
#define DEBUG_ATOI 0
#endif

#ifndef DEBUG_SOFTWARE_INTERRUPTS
#define DEBUG_SOFTWARE_INTERRUPTS 0
#endif

#ifndef DEBUG_SWITCH
#define DEBUG_SWITCH 0
#endif

#ifndef DEBUG_SYSCALL
#define DEBUG_SYSCALL 0
#endif

#ifndef DEBUG_USER_TRAPS
#define DEBUG_USER_TRAPS 0
#endif

#ifndef DEBUG_CLEAN_PROCESS
#define DEBUG_CLEAN_PROCESS 0
#endif

#ifndef DEBUG_SECTIONS
#define DEBUG_SECTIONS 0
#endif

#ifndef DEBUG_ALIGN
#define DEBUG_ALIGN 0
#endif

#ifndef DEBUG_EXIT
#define DEBUG_EXIT 0
#endif

#ifndef DEBUG_DEVICE_TREE
#define DEBUG_DEVICE_TREE 0
#endif

#ifndef DEBUG_DEVICE_TREE_SEARCH
#define DEBUG_DEVICE_TREE_SEARCH 0
#endif

#ifndef DEBUG_LIST
#define DEBUG_LIST 0
#endif

#ifndef DUMP_DEVICE_TREE
#define DUMP_DEVICE_TREE 0
#endif

#ifndef DEBUG_TESTS
#define DEBUG_TESTS 0
#endif

#ifndef DEBUG_TIMER_INTERRUPTS
#define DEBUG_TIMER_INTERRUPTS 0
#endif

#ifndef DEBUG_ALLOCATE_PROCESS
#define DEBUG_ALLOCATE_PROCESS 0
#endif

#ifndef EXIT_VIA_SBI
#define EXIT_VIA_SBI 0
#endif

#ifndef TIMER_INTERRUPT_DELAY
#define TIMER_INTERRUPT_DELAY 10000
#endif

#ifndef PAGE_TABLE_PRINT_ALL_FLAGS
#define PAGE_TABLE_PRINT_ALL_FLAGS 0
#endif

#ifndef EXAMPLE_PROCESSES_SPIN
#define EXAMPLE_PROCESSES_SPIN 1024
#endif

#ifndef EXAMPLE_PROCESSES_DISABLE
#define EXAMPLE_PROCESSES_DISABLE 0
#endif

#ifndef PANIC_LOOP
#define PANIC_LOOP 0
#endif

#ifndef TESTS_ENABLED
#define TESTS_ENABLED 0
#endif
