#pragma once

#include <stddef.h>
#include <stdint.h>

#include "util.h"  // IWYU pragma: keep, SECTION

enum SectionType {
    // normal program section
    SECTION_TYPE_NORMAL = 1,
    // meta-section, a section that contains other sections
    SECTION_TYPE_META = 2,
    // special section, mapped transparently for user processes
    SECTION_TYPE_SPECIAL = 3,
    // expanded user program
    SECTION_TYPE_USER_PROGRAM = 4,
};

typedef enum SectionType SectionType;

struct Section {
    char* name;
    SectionType type;
    uintptr_t start_address;
    uintptr_t end_address;
};
typedef struct Section Section;

#define SECTION_DECLARE(section)                     \
    extern const char CONCAT_(__##section, START)[]; \
    extern const char CONCAT_(__##section, END)[];   \
    extern const Section CONCAT_(SECTION, section)

#define SECTION_IMPL(section, TYPE)                              \
    const Section CONCAT_(SECTION, section) = {                  \
        .name = #section,                                        \
        .type = (TYPE),                                          \
        .start_address = (uintptr_t)CONCAT_(__##section, START), \
        .end_address = (uintptr_t)CONCAT_(__##section, END),     \
    }

// meta-sections
SECTION_DECLARE(MEMORY);
SECTION_DECLARE(USER_PROGRAMS);

// normal sections
SECTION_DECLARE(TEXT);
SECTION_DECLARE(RODATA);
SECTION_DECLARE(BSS);
SECTION_DECLARE(PAGES);

// special sections
SECTION_DECLARE(GLOBAL_SPECIAL);
SECTION_DECLARE(USER_SPECIAL);

// user program sections
// defined in autogenerated file
extern const Section* user_programs;
extern const size_t num_user_programs;

// places symbol in the global special page
#define IN_GLOBAL_SPECIAL SECTION(".global_special")
// places symbol in the user special page
#define IN_USER_SPECIAL SECTION(".user_special")

void print_all_sections(void);
void Section_print(const Section* section);
uintptr_t Section_size(const Section* section);
