[constants]
# (don't use g since it contains float and double)
# g = IMAFDZicsr_Zifencei

# i = base integer
# m = integer multiply and divide
# a = atomics
# zicsr = control and status registers
# zifencei = fence.i instruction (needed for opensbi)
# zicntr = counters
riscv_extensions = 'ima_zicsr_zifencei_zicntr'
riscv_code_model_arg = '-mcmodel=medany'
